DECLARE @CONTADOR	INT  = 0,
		@QUANTIDADE	INT = 100

SET NOCOUNT ON
WHILE ( @CONTADOR <= @QUANTIDADE)
BEGIN    
	INSERT INTO Produto (Descricao,DataCadastro) VALUES ('PRODUTO '+ CONVERT(VARCHAR,@CONTADOR), GETDATE())
    SET @CONTADOR  = @CONTADOR  + 1
END
SET NOCOUNT OFF

PRINT 'SUCESSO !'